In [1]:
pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

[1 2 3 4 5]


In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr_range = np.arange(0, 10, 2)  # Start at 0, end at 10 (exclusive), step by 2
print(arr_range)

[0 2 4 6 8]


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
result_add = arr1 + arr2
print(result_add)

# Element-wise multiplication
result_mult = arr1 * arr2
print(result_mult)

[5 7 9]
[ 4 10 18]


In [8]:
arr = np.array([10, 20, 30, 40, 50])

# Access the element at index 2
print(arr[2])

# Access elements from index 1 to 3 (exclusive)
print(arr[1:3])

30
[20 30]
